### ISSUE TITLE
listen EACCES 0.0.0.0:80

### ISSUE THREAD

**Issue by Starystars67** [FLYD3RS/fivem-web-rcon#1]
I have encountered an issue, not sure how this is solved i am on windows server 2012 (not r2)
![image](https://user-images.githubusercontent.com/15389482/31045138-aeaf0dfe-a5d4-11e7-8f55-ea9d22dedca8.png)

looks to be an issue because i am running something on post 80 is it going to cause an issue for me by changing the port?

**Comment by streads** [comment]
If something is already running on the port 80 then yes you need to change it.
Else you can remove the http server from this app and just reproduce an html interface inside your webserver.

**Comment by Starystars67** [comment]
I would need to remove the HTTP server then, how would you go about this?
